import Head from "next/head";
import type { NextPage } from "next";
import Homes from "@/pages/home/Home";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>SNS App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homes />
    </div>
  );
};

export default Home;
