import Head from "next/head";
import type { NextPage } from "next";
import Profile from "@/pages/Profile";
import Login from "@/pages/Login";
import Register from "@/pages/Register";
import Homes from "@/pages/Home";
import { useContext } from "react";
import { AuthContext } from "@/context/AuthContext";
// import { AuthContextProvider } from "@/context/AuthContext";

const Home: NextPage = () => {
  const { user } = useContext(AuthContext);
  return (
    <div>
      <Head>
        <title>SNS App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <AuthContextProvider>
      </AuthContextProvider> */}
      {/* <Homes /> */}
      {/* <Profile /> */}
      {user ? <Homes /> : <Login />}
      {/* <Login /> */}
      {/* <Register /> */}
    </div>
  );
};

export default Home;
