import Head from "next/head";
import type { NextPage } from "next";
import Homes from "@/pages/home/Home";
import Profile from "@/pages/profile/Profile";
import Login from "@/pages/login/Login";
import Register from "@/pages/register/Register";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>SNS App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homes />
      {/* <Profile /> */}
      {/* <Login /> */}
      {/* <Register /> */}
    </div>
  );
};

export default Home;
